# Generated by Django 4.2.6 on 2023-10-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='exec_datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
