# Generated by Django 4.2.6 on 2023-10-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_scraper_exec_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='exec_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
