# Generated by Django 4.2.6 on 2023-10-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_scraper_output_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='source_json_url_field',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scraper',
            name='source_urls',
            field=models.TextField(blank=True),
        ),
    ]
