# Generated by Django 4.2.6 on 2023-11-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_scraper_source_json_url_field_scraper_source_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='regex_sub',
            new_name='regex_sub_pattern',
        ),
        migrations.AddField(
            model_name='element',
            name='regex_sub_repl',
            field=models.TextField(blank=True),
        ),
    ]
