# Generated by Django 4.2.6 on 2023-11-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_scraper_in_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='in_favorites',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
