# Generated by Django 4.2.6 on 2023-11-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_scraper_source_json_url_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='source_scraper_urls_element',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
